apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
#This is what I was looking for dude
apiversion: v1
kind: Service
metadata:
  name: myervice
spec:
  name: service_for_new_pod